runtime: python39

entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT src.api.main:app

instance_class: F2

env_variables:
  MEMOTAG_ENV: "production"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
