option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: src.api.main:app
  aws:elasticbeanstalk:application:environment:
    PYTHONPATH: "/var/app/current"
    MEMOTAG_ENV: "production"
  aws:elasticbeanstalk:environment:
    LoadBalancerType: application
  aws:elasticbeanstalk:environment:proxy:
    ProxyServer: nginx

packages:
  yum:
    gcc: []
    make: []
    ffmpeg: []
    libsndfile: []

container_commands:
  01_setup_directories:
    command: "mkdir -p /var/app/current/data/db /var/app/current/data/recordings /var/app/current/reports"
  02_set_permissions:
    command: "chmod 755 -R /var/app/current/data"
