name: Memotag API CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest

  validate-render-config:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    steps:
      - name: Check Render API key
        run: |
          if [[ -z "${{ secrets.RENDER_API_KEY }}" ]]; then
            echo "::error::RENDER_API_KEY is not set in GitHub secrets. Please add it following the instructions in docs/render_deployment_setup.md"
            exit 1
          else
            echo "RENDER_API_KEY is configured correctly."
          fi

  deploy-staging:
    needs: [test, validate-render-config]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Render Staging
      uses: JorgeLNJunior/render-deploy@v1.4.3
      with:
        service_id: ${{ secrets.RENDER_STAGING_SERVICE_ID || 'memotag-staging' }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
        clear_cache: true
        deployment_environment: staging
        github_deployment: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-production:
    needs: [test, validate-render-config]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Render Production
      uses: JorgeLNJunior/render-deploy@v1.4.3
      with:
        service_id: ${{ secrets.RENDER_PRODUCTION_SERVICE_ID || 'memotag-8lja' }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
        clear_cache: true
        deployment_environment: production
        github_deployment: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
